AllCops:
  NewCops: disable

Style/FrozenStringLiteralComment: 
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20